/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examsystem;

import java.awt.Color;
import javax.swing.ButtonGroup;
/**
 *
 * @author cs
 */
public class exam extends javax.swing.JFrame {

    /**
     * Creates new form exam
     */
    public exam() {
        initComponents();
        ButtonGroup bg1=new ButtonGroup();
        bg1.add(rb11);
        bg1.add(rb12);
        bg1.add(rb13);
        bg1.add(rb14);
        ButtonGroup bg2=new ButtonGroup();
        bg2.add(rb21);
        bg2.add(rb22);
        bg2.add(rb23);
        bg2.add(rb24);
        ButtonGroup bg3=new ButtonGroup();
        bg3.add(rb31);
        bg3.add(rb32);
        bg3.add(rb33);
        bg3.add(rb34);
        ButtonGroup bg4=new ButtonGroup();
        bg4.add(rb41);
        bg4.add(rb42);
        bg4.add(rb43);
        bg4.add(rb44);
        ButtonGroup bg5=new ButtonGroup();
        bg5.add(rb51);
        bg5.add(rb52);
        bg5.add(rb53);
        bg5.add(rb54);
        ButtonGroup bg6=new ButtonGroup();
        bg6.add(rb61);
        bg6.add(rb62);
        bg6.add(rb63);
        bg6.add(rb64);
        ButtonGroup bg7=new ButtonGroup();
        bg7.add(rb71);
        bg7.add(rb72);
        bg7.add(rb73);
        bg7.add(rb74);
        ButtonGroup bg8=new ButtonGroup();
        bg8.add(rb81);
        bg8.add(rb82);
        bg8.add(rb83);
        bg8.add(rb84);
        ButtonGroup bg9=new ButtonGroup();
        bg9.add(rb91);
        bg9.add(rb92);
        bg9.add(rb93);
        bg9.add(rb94);
        ButtonGroup bg10=new ButtonGroup();
        bg10.add(rb101);
        bg10.add(rb102);
        bg10.add(rb103);
        bg10.add(rb104);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rb11 = new javax.swing.JRadioButton();
        rb14 = new javax.swing.JRadioButton();
        rb13 = new javax.swing.JRadioButton();
        rb12 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rb21 = new javax.swing.JRadioButton();
        rb22 = new javax.swing.JRadioButton();
        rb23 = new javax.swing.JRadioButton();
        rb24 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rb31 = new javax.swing.JRadioButton();
        rb32 = new javax.swing.JRadioButton();
        rb33 = new javax.swing.JRadioButton();
        rb34 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rb41 = new javax.swing.JRadioButton();
        rb42 = new javax.swing.JRadioButton();
        rb43 = new javax.swing.JRadioButton();
        rb44 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rb51 = new javax.swing.JRadioButton();
        rb52 = new javax.swing.JRadioButton();
        rb53 = new javax.swing.JRadioButton();
        rb54 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        rb61 = new javax.swing.JRadioButton();
        rb62 = new javax.swing.JRadioButton();
        rb63 = new javax.swing.JRadioButton();
        rb64 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        rb71 = new javax.swing.JRadioButton();
        rb72 = new javax.swing.JRadioButton();
        rb73 = new javax.swing.JRadioButton();
        rb74 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        rb81 = new javax.swing.JRadioButton();
        rb82 = new javax.swing.JRadioButton();
        rb83 = new javax.swing.JRadioButton();
        rb84 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        rb91 = new javax.swing.JRadioButton();
        rb92 = new javax.swing.JRadioButton();
        rb93 = new javax.swing.JRadioButton();
        rb94 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        rb101 = new javax.swing.JRadioButton();
        rb102 = new javax.swing.JRadioButton();
        rb103 = new javax.swing.JRadioButton();
        rb104 = new javax.swing.JRadioButton();
        q1 = new javax.swing.JLabel();
        q2 = new javax.swing.JLabel();
        q3 = new javax.swing.JLabel();
        q5 = new javax.swing.JLabel();
        q4 = new javax.swing.JLabel();
        q6 = new javax.swing.JLabel();
        q10 = new javax.swing.JLabel();
        q7 = new javax.swing.JLabel();
        q8 = new javax.swing.JLabel();
        q9 = new javax.swing.JLabel();
        attempt = new javax.swing.JLabel();
        att = new javax.swing.JLabel();
        remaining = new javax.swing.JLabel();
        rem = new javax.swing.JLabel();
        submit = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MCQ Exam");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(878, 31, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("1. Which of the following is the longest river in the world?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 112, -1, -1));

        rb11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb11.setText("Amazon River ");
        rb11.setOpaque(false);
        rb11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb11MouseClicked(evt);
            }
        });
        jPanel1.add(rb11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 149, -1, -1));

        rb14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb14.setText("Yangtze River");
        rb14.setOpaque(false);
        jPanel1.add(rb14, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 147, -1, -1));

        rb13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb13.setText("Mississippi River");
        rb13.setOpaque(false);
        jPanel1.add(rb13, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 147, -1, -1));

        rb12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb12.setText("Nile River");
        rb12.setOpaque(false);
        jPanel1.add(rb12, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 149, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("2. Mount Everest, the highest peak in the world, is located in which mountain range?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 197, -1, -1));

        rb21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb21.setText("Rocky Mountains");
        rb21.setOpaque(false);
        jPanel1.add(rb21, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 232, -1, -1));

        rb22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb22.setText("Andes Mountains");
        rb22.setOpaque(false);
        jPanel1.add(rb22, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 232, -1, -1));

        rb23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb23.setText("Himalayas");
        rb23.setOpaque(false);
        jPanel1.add(rb23, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 232, -1, -1));

        rb24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb24.setText("Alps");
        rb24.setOpaque(false);
        jPanel1.add(rb24, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 232, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("3. The Great Barrier Reef, one of the world's most extensive coral reef systems, is situated off the coast of which country?");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        rb31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb31.setText("Australia");
        rb31.setOpaque(false);
        jPanel1.add(rb31, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 315, -1, -1));

        rb32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb32.setText("Brazil");
        rb32.setOpaque(false);
        jPanel1.add(rb32, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 315, -1, -1));

        rb33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb33.setText("India");
        rb33.setOpaque(false);
        jPanel1.add(rb33, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 315, -1, -1));

        rb34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb34.setText("Mexico");
        rb34.setOpaque(false);
        jPanel1.add(rb34, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 315, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("4. The Sahara Desert is primarily located in which continent?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 371, -1, -1));

        rb41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb41.setText("Africa");
        rb41.setOpaque(false);
        jPanel1.add(rb41, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 414, -1, -1));

        rb42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb42.setText("Asia");
        rb42.setOpaque(false);
        rb42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb42ActionPerformed(evt);
            }
        });
        jPanel1.add(rb42, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 414, -1, -1));

        rb43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb43.setText("South America");
        rb43.setOpaque(false);
        jPanel1.add(rb43, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 414, -1, -1));

        rb44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb44.setText("Australia");
        rb44.setOpaque(false);
        jPanel1.add(rb44, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 414, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("5. The capital city of Japan is:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 466, -1, -1));

        rb51.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb51.setText("Beijing");
        rb51.setOpaque(false);
        jPanel1.add(rb51, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 501, -1, -1));

        rb52.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb52.setText("Tokyo");
        rb52.setOpaque(false);
        jPanel1.add(rb52, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 501, -1, -1));

        rb53.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb53.setText("Seoul");
        rb53.setOpaque(false);
        jPanel1.add(rb53, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 501, -1, -1));

        rb54.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb54.setText("Bangkok");
        rb54.setOpaque(false);
        jPanel1.add(rb54, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 501, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("6. The largest rainforest in the world is:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 557, -1, -1));

        rb61.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb61.setText("Amazon Rainforest");
        rb61.setOpaque(false);
        jPanel1.add(rb61, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 592, -1, -1));

        rb62.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb62.setText("Congo Rainforest");
        rb62.setOpaque(false);
        jPanel1.add(rb62, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 592, -1, -1));

        rb63.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb63.setText("Borneo Rainforest");
        rb63.setOpaque(false);
        jPanel1.add(rb63, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 592, -1, -1));

        rb64.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb64.setText("Daintree Rainforest");
        rb64.setOpaque(false);
        jPanel1.add(rb64, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 592, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("7. Which of the following countries does NOT border the Mediterranean Sea?");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 647, -1, -1));

        rb71.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb71.setText("Italy");
        rb71.setOpaque(false);
        jPanel1.add(rb71, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 686, -1, -1));

        rb72.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb72.setText("Greece");
        rb72.setOpaque(false);
        jPanel1.add(rb72, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 686, -1, -1));

        rb73.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb73.setText("Portugal");
        rb73.setOpaque(false);
        jPanel1.add(rb73, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 686, -1, -1));

        rb74.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb74.setText("Turkey ");
        rb74.setOpaque(false);
        jPanel1.add(rb74, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 686, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("8. Which of the following countries is known as the \"Land of the Rising Sun\"?");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 742, -1, -1));

        rb81.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb81.setText("China");
        rb81.setOpaque(false);
        jPanel1.add(rb81, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 777, -1, -1));

        rb82.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb82.setText("Japan");
        rb82.setOpaque(false);
        jPanel1.add(rb82, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 777, -1, -1));

        rb83.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb83.setText("South Korea");
        rb83.setOpaque(false);
        jPanel1.add(rb83, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 777, -1, -1));

        rb84.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb84.setText("Thailand");
        rb84.setOpaque(false);
        jPanel1.add(rb84, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 777, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("9. The Grand Canyon, a massive canyon carved by the Colorado River, is located in which U.S. state?");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 837, -1, -1));

        rb91.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb91.setText("Arizona");
        rb91.setOpaque(false);
        jPanel1.add(rb91, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 872, -1, -1));

        rb92.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb92.setText("Colorado");
        rb92.setOpaque(false);
        jPanel1.add(rb92, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 872, -1, -1));

        rb93.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb93.setText("California");
        rb93.setOpaque(false);
        jPanel1.add(rb93, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 872, -1, -1));

        rb94.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb94.setText("New Mexico");
        rb94.setOpaque(false);
        jPanel1.add(rb94, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 872, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("10. Which of the following countries is the largest by land area?");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 933, -1, -1));

        rb101.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb101.setText("US");
        rb101.setOpaque(false);
        rb101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb101ActionPerformed(evt);
            }
        });
        jPanel1.add(rb101, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 968, -1, -1));

        rb102.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb102.setText("Russia");
        rb102.setOpaque(false);
        jPanel1.add(rb102, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 968, -1, -1));

        rb103.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb103.setText("Canada");
        rb103.setOpaque(false);
        rb103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb103ActionPerformed(evt);
            }
        });
        jPanel1.add(rb103, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 968, -1, -1));

        rb104.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb104.setText("China");
        rb104.setOpaque(false);
        jPanel1.add(rb104, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 968, -1, -1));

        q1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        q1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q1.setText("1");
        q1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        q1.setOpaque(true);
        jPanel1.add(q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1393, 100, 34, 32));

        q2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        q2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q2.setText("2");
        q2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        q2.setOpaque(true);
        jPanel1.add(q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1517, 100, 34, 32));

        q3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        q3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q3.setText("3");
        q3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        q3.setOpaque(true);
        jPanel1.add(q3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 100, 34, 32));

        q5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        q5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q5.setText("5");
        q5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        q5.setOpaque(true);
        jPanel1.add(q5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1517, 174, 34, 32));

        q4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        q4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q4.setText("4");
        q4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        q4.setOpaque(true);
        jPanel1.add(q4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1393, 174, 34, 32));

        q6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        q6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q6.setText("6");
        q6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        q6.setOpaque(true);
        jPanel1.add(q6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 174, 34, 32));

        q10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        q10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q10.setText("10");
        q10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        q10.setOpaque(true);
        jPanel1.add(q10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1393, 319, 34, 32));

        q7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        q7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q7.setText("7");
        q7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        q7.setOpaque(true);
        jPanel1.add(q7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1393, 245, 34, 32));

        q8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        q8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q8.setText("8");
        q8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        q8.setOpaque(true);
        jPanel1.add(q8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1517, 245, 34, 32));

        q9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        q9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q9.setText("9");
        q9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        q9.setOpaque(true);
        jPanel1.add(q9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 245, 34, 32));

        attempt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        attempt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attempt.setText("Total Attempt");
        attempt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(attempt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1476, 443, 137, 32));

        att.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        att.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        att.setText("0");
        att.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(att, new org.netbeans.lib.awtextra.AbsoluteConstraints(1524, 488, 34, 32));

        remaining.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        remaining.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        remaining.setText("Remaining");
        remaining.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(remaining, new org.netbeans.lib.awtextra.AbsoluteConstraints(1476, 538, 137, 32));

        rem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rem.setText("10");
        rem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(rem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1524, 583, 34, 32));

        submit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        submit.setText("Submit Answer");
        submit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitMouseExited(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 850, 137, 32));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examsystem/examimage.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 920, 980));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examsystem/examimage.png"))); // NOI18N
        jLabel14.setOpaque(true);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 80, 470, 990));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examsystem/exam2.png"))); // NOI18N
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb42ActionPerformed

    private void rb101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb101ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb101ActionPerformed

    private void rb103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb103ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb103ActionPerformed

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        int point=0,count=0;
        if(rb12.isSelected()){
            point=point+2;
            count++;
        }
        else
            point--;
        if(rb23.isSelected()){
            point=point+2;
            count++;
        }
        else
            point--;
        if(rb31.isSelected()){
            point=point+2;
            count++;
        }
        else
            point--;
        if(rb41.isSelected()){
           point=point+2;
           count++;
        }
        else
            point--;
        if(rb52.isSelected()){
           point=point+2;
           count++;
        }
        else
            point--;
        if(rb61.isSelected()){
           point=point+2;
           count++;
        }
        else
            point--;
        if(rb73.isSelected()){
          point=point+2;
          count++;
        }
        else
            point--;
        if(rb82.isSelected()){
          point=point+2;
          count++;
        }
        else
            point--;
        if(rb91.isSelected()){
           point=point+2;
           count++;
        }
        else
            point--;
        if(rb102.isSelected()){
            point=point+2;
            count++;
        }
        else
            point--;
           
        
        score sc=new score(point, count);
        sc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_submitMouseClicked

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
         int count=0;                    
        if(rb11.isSelected() || rb12.isSelected() || rb13.isSelected() || rb14.isSelected()){
            q1.setBackground(Color.green);
             att.setText(String.valueOf(++count));
            rem.setText(String.valueOf(10-count));
        }
        else{
            q1.setBackground(Color.red);
        }
        if(rb21.isSelected() || rb22.isSelected() || rb23.isSelected() || rb24.isSelected()){
            q2.setBackground(Color.green);
            att.setText(String.valueOf(++count));
            rem.setText(String.valueOf(10-count));
        }
        else{
            q2.setBackground(Color.red);
        }
        if(rb31.isSelected() || rb32.isSelected() || rb33.isSelected() || rb34.isSelected()){
            q3.setBackground(Color.green);
            att.setText(String.valueOf(++count));
            rem.setText(String.valueOf(10-count));
        }
        else{
            q3.setBackground(Color.red);
        }
        if(rb41.isSelected() || rb42.isSelected() || rb43.isSelected() || rb44.isSelected()){
            q4.setBackground(Color.green);
            att.setText(String.valueOf(++count));
            rem.setText(String.valueOf(10-count));
        }
        else{
            q4.setBackground(Color.red);
        }
        if(rb51.isSelected() || rb52.isSelected() || rb53.isSelected() || rb54.isSelected()){
            q5.setBackground(Color.green);
            att.setText(String.valueOf(++count));
            rem.setText(String.valueOf(10-count));
        }
        else{
            q5.setBackground(Color.red);
        }
        if(rb61.isSelected() || rb62.isSelected() || rb63.isSelected() || rb64.isSelected()){
            q6.setBackground(Color.green);
            att.setText(String.valueOf(++count));
            rem.setText(String.valueOf(10-count));
        }
        else{
            q6.setBackground(Color.red);
        }
        if(rb71.isSelected() || rb72.isSelected() || rb73.isSelected() || rb74.isSelected()){
            q7.setBackground(Color.green);
            att.setText(String.valueOf(++count));
            rem.setText(String.valueOf(10-count));
        }
        else{
            q7.setBackground(Color.red);
            q7.setForeground(Color.black);
        }
        if(rb81.isSelected() || rb82.isSelected() || rb83.isSelected() || rb84.isSelected()){
            q8.setBackground(Color.green);
            att.setText(String.valueOf(++count));
            rem.setText(String.valueOf(10-count));
        }
        else{
            q8.setBackground(Color.red);
        }
        if(rb91.isSelected() || rb92.isSelected() || rb93.isSelected() || rb94.isSelected()){
            q9.setBackground(Color.green);
            att.setText(String.valueOf(++count));
            rem.setText(String.valueOf(10-count));
        }
        else{
            q9.setBackground(Color.red);
        }
        if(rb101.isSelected() || rb102.isSelected() || rb103.isSelected() || rb104.isSelected()){
            q10.setBackground(Color.green);
            att.setText(String.valueOf(++count));
            rem.setText(String.valueOf(10-count));
        }
        else{
            q10.setBackground(Color.red);
        }
    }//GEN-LAST:event_jLabel13MouseEntered

    private void rb11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb11MouseClicked

    }//GEN-LAST:event_rb11MouseClicked

    private void submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseEntered
       submit.setText("<html><u>Submit Answer</u><html>");
    }//GEN-LAST:event_submitMouseEntered

    private void submitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseExited
      submit.setText("Submit Answer");
    }//GEN-LAST:event_submitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel att;
    private javax.swing.JLabel attempt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel q1;
    private javax.swing.JLabel q10;
    private javax.swing.JLabel q2;
    private javax.swing.JLabel q3;
    private javax.swing.JLabel q4;
    private javax.swing.JLabel q5;
    private javax.swing.JLabel q6;
    private javax.swing.JLabel q7;
    private javax.swing.JLabel q8;
    private javax.swing.JLabel q9;
    private javax.swing.JRadioButton rb101;
    private javax.swing.JRadioButton rb102;
    private javax.swing.JRadioButton rb103;
    private javax.swing.JRadioButton rb104;
    private javax.swing.JRadioButton rb11;
    private javax.swing.JRadioButton rb12;
    private javax.swing.JRadioButton rb13;
    private javax.swing.JRadioButton rb14;
    private javax.swing.JRadioButton rb21;
    private javax.swing.JRadioButton rb22;
    private javax.swing.JRadioButton rb23;
    private javax.swing.JRadioButton rb24;
    private javax.swing.JRadioButton rb31;
    private javax.swing.JRadioButton rb32;
    private javax.swing.JRadioButton rb33;
    private javax.swing.JRadioButton rb34;
    private javax.swing.JRadioButton rb41;
    private javax.swing.JRadioButton rb42;
    private javax.swing.JRadioButton rb43;
    private javax.swing.JRadioButton rb44;
    private javax.swing.JRadioButton rb51;
    private javax.swing.JRadioButton rb52;
    private javax.swing.JRadioButton rb53;
    private javax.swing.JRadioButton rb54;
    private javax.swing.JRadioButton rb61;
    private javax.swing.JRadioButton rb62;
    private javax.swing.JRadioButton rb63;
    private javax.swing.JRadioButton rb64;
    private javax.swing.JRadioButton rb71;
    private javax.swing.JRadioButton rb72;
    private javax.swing.JRadioButton rb73;
    private javax.swing.JRadioButton rb74;
    private javax.swing.JRadioButton rb81;
    private javax.swing.JRadioButton rb82;
    private javax.swing.JRadioButton rb83;
    private javax.swing.JRadioButton rb84;
    private javax.swing.JRadioButton rb91;
    private javax.swing.JRadioButton rb92;
    private javax.swing.JRadioButton rb93;
    private javax.swing.JRadioButton rb94;
    private javax.swing.JLabel rem;
    private javax.swing.JLabel remaining;
    private javax.swing.JLabel submit;
    // End of variables declaration//GEN-END:variables
}
