/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examsystem;

import java.awt.Cursor;
import java.awt.Font;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;

/**
 *
 * @author cs
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        admin = new javax.swing.JLabel();
        stu = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        info = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(240, 233, 215));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        home.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examsystem/home1.png"))); // NOI18N
        home.setText("    Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        jPanel3.add(home);
        home.setBounds(22, 125, 102, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examsystem/down arrow.png"))); // NOI18N
        jLabel7.setText("      User");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(24, 190, 100, 25);

        admin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        admin.setText("Admin");
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminMouseExited(evt);
            }
        });
        jPanel3.add(admin);
        admin.setBounds(70, 240, 60, 22);

        stu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stu.setText("Student");
        stu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stuMouseExited(evt);
            }
        });
        jPanel3.add(stu);
        stu.setBounds(60, 290, 71, 22);

        contact.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        contact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examsystem/contact.png"))); // NOI18N
        contact.setText("  Contact");
        contact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactMouseExited(evt);
            }
        });
        jPanel3.add(contact);
        contact.setBounds(20, 400, 110, 30);

        info.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examsystem/about.png"))); // NOI18N
        info.setText("    Info");
        info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infoMouseExited(evt);
            }
        });
        jPanel3.add(info);
        info.setBounds(30, 340, 100, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 150, 1080);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setText("Welcome To MCQ Examination Center");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(250, 150, 740, 44);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Don't use the wrong information in registration.");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(250, 360, 600, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("A Student is required to register herself/himself to avail different");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(250, 240, 600, 22);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("services under MCQ practice test.");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(250, 280, 600, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Multiple registration are restricted by a single user.");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(250, 320, 600, 22);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examsystem/study2.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, 0, 1920, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
         Admin_login log=new Admin_login();
         log.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_adminMouseClicked

    private void adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseEntered
       admin.setText("<html><u>Admin</u><html>");
    }//GEN-LAST:event_adminMouseEntered

    private void stuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stuMouseClicked
         Student_login log=new Student_login();
         log.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_stuMouseClicked

    private void infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMouseClicked
        info log=new info();
         log.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_infoMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        Admin_login log=new Admin_login();
         this.setVisible(false);
         this.setVisible(true);
    }//GEN-LAST:event_homeMouseClicked

    private void stuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stuMouseEntered
       stu.setText("<html><u>Student</u><html>");
    }//GEN-LAST:event_stuMouseEntered

    private void infoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMouseEntered
       info.setText("<html><u>&nbsp; &nbsp; Info</u><html>");
    }//GEN-LAST:event_infoMouseEntered

    private void contactMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMouseEntered
        contact.setText("<html><u>&nbsp; Contact</u><html>");
    }//GEN-LAST:event_contactMouseEntered

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        home.setText("<html><u>&nbsp; &nbsp; Home</u><html>");
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
       home.setText("    Home");
    }//GEN-LAST:event_homeMouseExited

    private void adminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseExited
       admin.setText("Admin");
    }//GEN-LAST:event_adminMouseExited

    private void stuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stuMouseExited
        stu.setText("Student");
    }//GEN-LAST:event_stuMouseExited

    private void infoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMouseExited
      info.setText("    Info");
    }//GEN-LAST:event_infoMouseExited

    private void contactMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMouseExited
        contact.setText("  Contact");
    }//GEN-LAST:event_contactMouseExited

    private void contactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMouseClicked
       contactus cu=new contactus();
       cu.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_contactMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel home;
    private javax.swing.JLabel info;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel stu;
    // End of variables declaration//GEN-END:variables
}
