/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author cs
 */
public class student_dashboard extends javax.swing.JFrame {
        String user1;
    /**
     * Creates new form student_dashboard
     * @param user
     */
    public student_dashboard(String user) {
        initComponents();
        this.user1=user;
        String fullname="";
        String fname="";
        String mname="";
        String lname="";
        String email_id="";
         try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","Pandit1234");
            PreparedStatement ps=con.prepareStatement("SELECT first_name,middle_name,last_name,email_id FROM student WHERE first_name=?");
            ps.setString(1,user);
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                fname=rs.getString("FIRST_NAME");
                mname=rs.getString("MIDDLE_NAME");
                lname=rs.getString("LAST_NAME");
                email_id=rs.getString("EMAIL_ID");
            }
            if(mname !=null)
            fullname= fname +" "+ mname +" "+ lname;
            else
            fullname= fname +" "+ lname;
            name.setText("Name : "+fullname);
            uname.setText("User name : "+fname);
            email.setText("Email id : "+email_id);
            wel.setText("Welcom "+fullname);
            con.close();
        }catch(ClassNotFoundException | SQLException e){
            System.out.println(e);
        }
    }

    public student_dashboard() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        wel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        reset = new javax.swing.JLabel();
        start = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 900));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Profile");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(260, 160, 80, 29);

        name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name.setText("Name");
        name.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                namePropertyChange(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(120, 470, 310, 22);

        uname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        uname.setText("User name");
        jPanel1.add(uname);
        uname.setBounds(120, 510, 320, 22);

        email.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        email.setText("Email id");
        email.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.add(email);
        email.setBounds(120, 550, 320, 22);

        wel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        wel.setText("welcome");
        jPanel1.add(wel);
        wel.setBounds(720, 250, 520, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Read all the Instruction carefully and click start button for start the exam.");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(680, 320, 669, 22);

        reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reset.setText("Reset Password");
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resetMouseExited(evt);
            }
        });
        jPanel1.add(reset);
        reset.setBounds(230, 680, 143, 22);

        start.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        start.setText("Start Exam");
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                startMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                startMouseExited(evt);
            }
        });
        jPanel1.add(start);
        start.setBounds(1230, 860, 99, 22);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Understand whether correct answers gain you 2 points, and if there are 1 negative marks for incorrect answers. ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(720, 410, 1017, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Marking Scheme:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(680, 370, 158, 22);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Stay Calm and Focused: ");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(680, 470, 219, 22);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Maintain your composure throughout the test. Avoid getting stuck on difficult questions and manage your time wisely.  ");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(720, 510, 1074, 22);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("In most cases, it's better to attempt every question, even if you're unsure. Leaving questions unanswered guarantees");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(720, 600, 1070, 22);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Do Not Skip Questions:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(680, 560, 207, 22);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("following the instructions properly can lead to a fair evaluation of your knowledge and skills. Good luck with your MCQ test!");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(680, 740, 1110, 22);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel17.setText("Student dashboard");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(1090, 160, 370, 44);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("no points, while a guess might still give you a chance. ");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(720, 640, 487, 22);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examsystem/profile1.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(200, 220, 210, 200);

        logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(270, 640, 62, 22);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examsystem/back1.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(90, 140, 30, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examsystem/dash.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1920, 1080);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
       Student_changepassword sc=new Student_changepassword(user1);
       sc.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_resetMouseClicked

    private void namePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_namePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_namePropertyChange

    private void resetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseEntered
        reset.setText("<html><u>Reset Password</u><html>");
    }//GEN-LAST:event_resetMouseEntered

    private void resetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseExited
       reset.setText("Reset Password");
    }//GEN-LAST:event_resetMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Student_login sl=new Student_login();
       sl.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
       logout.setText("<html><u>Logout</u><html>");
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setText("Logout");
    }//GEN-LAST:event_logoutMouseExited

    private void startMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseEntered
        start.setText("<html><u>Start Exam</u><html>");
    }//GEN-LAST:event_startMouseEntered

    private void startMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseExited
        start.setText("Start Exam");
    }//GEN-LAST:event_startMouseExited

    private void startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseClicked
      exam ex=new exam();
      ex.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_startMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        Home ho=new Home();
        ho.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        
    }//GEN-LAST:event_backMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    public static javax.swing.JLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logout;
    public static javax.swing.JLabel name;
    private javax.swing.JLabel reset;
    private javax.swing.JLabel start;
    public static javax.swing.JLabel uname;
    private javax.swing.JLabel wel;
    // End of variables declaration//GEN-END:variables
}