/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examsystem;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;

/**
 *
 * @author Asus
 */
public class Student_Register extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Student_Register() {
        initComponents();
        ButtonGroup bg=new ButtonGroup();
        bg.add(male);
        bg.add(female);
        bg.add(other);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        mname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        school = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        other = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        qua = new javax.swing.JComboBox<>();
        reset = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        back = new javax.swing.JLabel();
        alert = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("First Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(720, 230, 97, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Middle Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(720, 300, 117, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(720, 360, 95, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Highest Qualification");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(720, 420, 189, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("School/College Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(720, 480, 194, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Gender");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(720, 540, 66, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Email ID");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(720, 610, 77, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Phone No");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(720, 670, 88, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Enter Password");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(720, 740, 141, 22);

        pass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(pass);
        pass.setBounds(970, 730, 260, 28);

        fname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(fname);
        fname.setBounds(970, 230, 260, 26);

        mname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(mname);
        mname.setBounds(970, 290, 260, 28);

        lname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lname);
        lname.setBounds(970, 350, 260, 28);

        school.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        school.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(school);
        school.setBounds(970, 480, 260, 28);

        email.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(email);
        email.setBounds(970, 600, 260, 28);

        phone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        phone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        jPanel1.add(phone);
        phone.setBounds(970, 670, 260, 28);

        other.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        other.setText("Other");
        other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherActionPerformed(evt);
            }
        });
        jPanel1.add(other);
        other.setBounds(1150, 540, 80, 31);

        male.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male);
        male.setBounds(970, 540, 80, 31);

        female.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female);
        female.setBounds(1050, 540, 100, 31);

        qua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        qua.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Qualification", "10th", "Deploma", "+2", "BCA", "BSC", "BBA", "B-Tech", "MCA", "MBA", "other" }));
        qua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quaActionPerformed(evt);
            }
        });
        jPanel1.add(qua);
        qua.setBounds(970, 420, 260, 30);

        reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reset.setText("Reset");
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset);
        reset.setBounds(760, 830, 90, 31);

        submit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit);
        submit.setBounds(1040, 830, 95, 31);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examsystem/back1.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(90, 50, 30, 30);

        alert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        alert.setText("Do not fill the wrong information");
        jPanel1.add(alert);
        alert.setBounds(790, 920, 450, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examsystem/finger.png"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(720, 920, 30, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setText("Student Registration Form");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(720, 100, 500, 50);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("*");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(690, 740, 30, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("*");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(690, 230, 30, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("*");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(690, 360, 30, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("*");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(690, 420, 30, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("*");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(690, 480, 30, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("*");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(690, 540, 30, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("*");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(690, 610, 30, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("*");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(690, 670, 30, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examsystem/register.png"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(0, 0, 1930, 1080);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static boolean schoolname(String str){
    String regex="^[a-zA-Z\\s]+$";
    Pattern p=Pattern.compile(regex);
    Matcher m=p.matcher(str);
    return m.matches();
}
    public static boolean containletter(String str){
    String regex="^[a-zA-Z]+$";
    Pattern p=Pattern.compile(regex);
    Matcher m=p.matcher(str);
    return m.matches();
}
public static boolean containNumber(String str){
    String regex="^[0-9]+$";
       Pattern p=Pattern.compile(regex);
       Matcher m=p.matcher(str);
    return m.matches();
}
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
       String gender;
       String pho=phone.getText();
       long pn;
       if(!pho.isEmpty())
        pn=Long.parseLong(String.valueOf(pho));
       else
           pn=0;
        if(male.isSelected())
             gender= "Male";
        else if(female.isSelected())
            gender="Female";
        else
            gender="other";
        if("".equals(fname.getText()) || "".equals(school.getText()) || "".equals(email.getText()) || "".equals(phone.getText()) || "".equals(pass.getText()) || "".equals(lname.getText()) ){
            alert.setText("Fill up all the details");
            alert.setForeground(Color.red);
        }
        else if("".equals(mname.getText()) && "".equals(lname.getText()) || !"".equals(mname.getText()) && "".equals(lname.getText())){
             alert.setText("Fill the last name");
            alert.setForeground(Color.red);
        }
        else if(fname.getText().contains(" ")){
            alert.setText("First Name not contain space");
            alert.setForeground(Color.red);
        }
        else if(mname.getText().contains(" ")){
            alert.setText("Middle Name not contain space");
            alert.setForeground(Color.red);
        }
        else if(lname.getText().contains(" ")){
            alert.setText("Last Name not contain space");
            alert.setForeground(Color.red);
        }
        else if(!containletter(fname.getText())){
            alert.setText("First Name only contains Alphabet");
            alert.setForeground(Color.red);
        }
       
        else if(!containletter(lname.getText())){
            alert.setText("Last Name only contains Alphabet");
            alert.setForeground(Color.red);
        }
        else if(!schoolname(school.getText())){
            alert.setText("School Name not contains number");
            alert.setForeground(Color.red);
        }
        else if(!email.getText().contains("@")){
            alert.setText("Email must contain @");
            alert.setForeground(Color.red);
        }
        else if(email.getText().contains(" ")){
            alert.setText("Email not contain space");
            alert.setForeground(Color.red);
        }
        else if(pn> 9999999999L || pn <999999999){
            alert.setText("Phone Number is about 10 digit");
            alert.setForeground(Color.red);
        }
        else if(!containNumber(phone.getText())){
            alert.setText("Phone Number only contains number");
            alert.setForeground(Color.red);
        }
        else if(containletter(phone.getText())){
            alert.setText("Phone Number only contains number");
            alert.setForeground(Color.red);
        }
        else if(!male.isSelected() && !female.isSelected() && !other.isSelected()){
             alert.setText("Select the gender");
            alert.setForeground(Color.red);
        }
        else if("Qualification".equals((String)qua.getSelectedItem())){
            alert.setText("Select the Qualification");
            alert.setForeground(Color.red);
        }
        else{
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","Pandit1234");
            PreparedStatement ps=con.prepareStatement("insert into student values(?,?,?,?,?,?,?,?,?)");
            ps.setString(1,fname.getText());
            ps.setString(2,mname.getText());
            ps.setString(3,lname.getText());
            ps.setString(4,(String)qua.getSelectedItem());
            ps.setString(5,school.getText());
            ps.setString(6,gender);
            ps.setString(7,email.getText());
            ps.setString(8,phone.getText());
            ps.setString(9,pass.getText());
            Statement stm=con.createStatement();
            ResultSet rs=stm.executeQuery("Select * from student");
            while(rs.next()){
            if(phone.getText().equals(rs.getString(8)) || email.getText().equals(rs.getString(7)))
            {
                alert.setText("Already exist");
               alert.setForeground(Color.red);
               con.close();
            }
            else{
            }
            }
            ps.executeUpdate();
            alert.setText("Data Inserted Sucessfully");
            alert.setForeground(Color.blue);
            con.close();
        }
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e);
        }
                }
    }//GEN-LAST:event_submitActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
       
    }//GEN-LAST:event_phoneActionPerformed

    private void quaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quaActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
     fname.setText("");
     mname.setText("");
     lname.setText("");
     qua.setSelectedIndex(0);
     school .setText("");
     email.setText("");
     phone.setText("");
     pass.setText("");
     alert.setText("Do not fill the wrong information");
     alert.setForeground(Color.black);
    }//GEN-LAST:event_resetActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed

    }//GEN-LAST:event_femaleActionPerformed

    private void otherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherActionPerformed
    }//GEN-LAST:event_otherActionPerformed

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        ButtonGroup bg=new ButtonGroup();
        bg.add(male);
        bg.add(female);
        bg.add(other);    
        bg.clearSelection();
    }//GEN-LAST:event_resetMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
       Student_login sl=new Student_login();
       sl.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        
    }//GEN-LAST:event_backMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert;
    private javax.swing.JLabel back;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField lname;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mname;
    private javax.swing.JRadioButton other;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField phone;
    private javax.swing.JComboBox<String> qua;
    private javax.swing.JButton reset;
    private javax.swing.JTextField school;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
